# Generated by Django 4.1 on 2022-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220816_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку рецепта', null=True, upload_to='media/', verbose_name='Картинка'),
        ),
    ]
